version: "3.5"
services:
  spring-boot-app:
    image: spring-boot-image
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - "8080:8080"
    volumes:
      - $HOME/.m2/repository:/root/.m2/repository
      - /data/spring-boot