---

- name: "Download node exporter"
  get_url:
    url: https://github.com/prometheus/node_exporter/releases/download/v1.4.0/node_exporter-1.4.0.linux-amd64.tar.gz
    dest: /tmp
  
- name: "Unarchive node exporter"
  unarchive:
    src: /tmp/node_exporter-1.4.0.linux-amd64.tar.gz
    dest: /tmp
    remote_src: yes

- name: "Move node exporter to /usr/local/bin"
  copy:
    src: "/tmp/node_exporter-1.4.0.linux-amd64/node_exporter"
    dest: "/usr/local/bin/node_exporter"
    remote_src: yes
    owner: root
    group: root
    mode: 0755

- name: "Install unit file to systemd"
  template:
    src: templates/node_exporter.service.j2
    dest: /etc/systemd/system/node_exporter.service
    owner: root
    group: root
    mode: 0600

- name: "Start node exporter"
  systemd:
    daemon_reload: yes
    enabled: yes
    state: started
    name: node_exporter.service


# tasks file for node_exporter
